[package]
name = "wasmcloud-api-types"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lattice-proto-formatter"
test = false
bench = false
required-features = ["cli"]

[features]
cli = ["clap"]

[dependencies]
async-nats = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, optional = true }
prost = { workspace = true, features = ["derive"]}
prost-types = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { version = "0.13"}
